app1/urls.py
from django.urls import path
from app1.views import *
app_name='somthing'

urlpatterns = [
    path('kishore/',kishore,name='kishore'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='nothing'

urlpatterns = [
    path('nani/',nani,name='nani'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def kishore(request):
    return render(request,'kishore.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def nani(request):
    return render(request,'nani.html')

templates/kishore.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hii hello</h1>
        <a href="{% url 'nothing:nani' %}"><h1>response</h1></a>
    </center>
</body>
</html>

templates/nani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hii </h1>
        <a href="{% url 'somthing:kishore' %}"><h1>response</h1></a>
    </center>
</body>
</html>